#pragma once

#if __has_include("LocalConfig.h")
#include "LocalConfig.h"
#endif

#ifndef TCALL_WIFI_SSID
#define TCALL_WIFI_SSID ""
#endif

#ifndef TCALL_WIFI_PASSWORD
#define TCALL_WIFI_PASSWORD ""
#endif

#ifndef TCALL_OTA_HOSTNAME
#define TCALL_OTA_HOSTNAME "tcall-a7670-v10"
#endif

#ifndef TCALL_DEVICE_ID
#define TCALL_DEVICE_ID "eboxster"
#endif

#ifndef TCALL_SIM_PIN
#define TCALL_SIM_PIN ""
#endif

#ifndef TCALL_APN
#define TCALL_APN ""
#endif

#ifndef TCALL_APN_USER
#define TCALL_APN_USER ""
#endif

#ifndef TCALL_APN_PASS
#define TCALL_APN_PASS ""
#endif

#ifndef TCALL_PDP_TYPE
#define TCALL_PDP_TYPE "IPV4V6"
#endif

#ifndef TCALL_MQTT_HOST
#define TCALL_MQTT_HOST ""
#endif

#ifndef TCALL_MQTT_CELLULAR_HOST
#define TCALL_MQTT_CELLULAR_HOST TCALL_MQTT_HOST
#endif

#ifndef TCALL_MQTT_CELLULAR_PORT
#define TCALL_MQTT_CELLULAR_PORT TCALL_MQTT_PORT
#endif

#ifndef TCALL_MQTT_CELLULAR_NATIVE
#define TCALL_MQTT_CELLULAR_NATIVE 1
#endif

#ifndef TCALL_MQTT_TRANSPORT
#define TCALL_MQTT_TRANSPORT "wifi"
#endif

#ifndef TCALL_MQTT_PORT
#define TCALL_MQTT_PORT 1883
#endif

#ifndef TCALL_MQTT_USER
#define TCALL_MQTT_USER ""
#endif

#ifndef TCALL_MQTT_PASS
#define TCALL_MQTT_PASS ""
#endif

#ifndef TCALL_MQTT_CLIENT_ID
#define TCALL_MQTT_CLIENT_ID TCALL_DEVICE_ID
#endif

#ifndef TCALL_MQTT_TOPIC_PREFIX
#define TCALL_MQTT_TOPIC_PREFIX TCALL_DEVICE_ID
#endif

#ifndef TCALL_MQTT_PUBLISH_INTERVAL_MS
#define TCALL_MQTT_PUBLISH_INTERVAL_MS 10000UL
#endif

#ifndef TCALL_GPS_AUTOSTART
#define TCALL_GPS_AUTOSTART 0
#endif

#ifndef TCALL_REMOTE_DEVICE_MANAGER_ENABLED
#define TCALL_REMOTE_DEVICE_MANAGER_ENABLED 1
#endif

#ifndef TCALL_RDM_LTE_ALIVE_AUTOSTART
#define TCALL_RDM_LTE_ALIVE_AUTOSTART 1
#endif

#ifndef TCALL_FW_VERSION
#define TCALL_FW_VERSION "dev"
#endif

#ifndef TCALL_GITHUB_OTA_OWNER
#define TCALL_GITHUB_OTA_OWNER ""
#endif

#ifndef TCALL_GITHUB_OTA_REPO
#define TCALL_GITHUB_OTA_REPO ""
#endif

#ifndef TCALL_GITHUB_OTA_BIN_ASSET
#define TCALL_GITHUB_OTA_BIN_ASSET ""
#endif

#ifndef TCALL_GITHUB_OTA_CRC_ASSET
#define TCALL_GITHUB_OTA_CRC_ASSET ""
#endif

#ifndef TCALL_GITHUB_OTA_USER_AGENT
#define TCALL_GITHUB_OTA_USER_AGENT "ESP32S3-TCU-LTE-OTA-Demo"
#endif

#ifndef TCALL_GITHUB_OTA_REBOOT_AFTER_UPDATE
#define TCALL_GITHUB_OTA_REBOOT_AFTER_UPDATE 1
#endif
